name: Devops Workflow

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Filename to be created"
        required: true
        default: "test.txt"
      input_string:
        description: "Text to be written to file"
        required: true
        default: "Hello Wordl!"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "nginx.conf,*.sh"
          target: "/home/ubuntu/"

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ' ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}'
          privateKey: ${{ secrets.EC2_SSH_KEY }}
          command: |
            ls -alrt
            chmod +x *.sh
            ls -alrt
            ./file.sh ${{ inputs.filename }} ${{ inputs.input_string }}
            ./webserver.sh  
          
      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2.1.0
      #   with:
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}
  
      # - name: Execute file Script
      #   run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} bash file.sh ${{ inputs.filename }} ${{ inputs.input_string }}

      # - name: Execute webserver Script
      #   run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} bash webserver.sh
